cflags= /ox /g5 /c /nologo /w0

all:
fl32 $(cflags) abc.for 
fl32 $(cflags) compu.for
fl32 $(cflags) conlin.for
fl32 $(cflags) contr.for
fl32 $(cflags) coord.for
fl32 $(cflags) copy.for
fl32 $(cflags) costmain.for
fl32 $(cflags) darg.for
fl32 $(cflags) dargsr.for
fl32 $(cflags) deriv.for
fl32 $(cflags) dhydro.for
fl32 $(cflags) dhyp.for
fl32 $(cflags) dhyps.for
fl32 $(cflags) discu.for
fl32 $(cflags) dloc.for
fl32 $(cflags) dlocy.for
fl32 $(cflags) dlocz.for
fl32 $(cflags) dmom.for
fl32 $(cflags) dmomsr.for
fl32 $(cflags) dpar.for
fl32 $(cflags) dpress.for
fl32 $(cflags) ecri.for
fl32 $(cflags) ecri2.for
fl32 $(cflags) ecri3.for
fl32 $(cflags) ecri4.for
fl32 $(cflags) entete.for
fl32 $(cflags) ents.for
fl32 $(cflags) equil.for
fl32 $(cflags) flamb.for
fl32 $(cflags) geom.for
fl32 $(cflags) graphic.for
fl32 $(cflags) hughes.for
fl32 $(cflags) hull.for
fl32 $(cflags) hydro.for
fl32 $(cflags) hyp1.for
fl32 $(cflags) hyp2.for
fl32 $(cflags) inteq.for
fl32 $(cflags) lbr5.for
fl32 $(cflags) linde.for
fl32 $(cflags) linea.for
fl32 $(cflags) loc.for
fl32 $(cflags) locy.for
fl32 $(cflags) locz.for
fl32 $(cflags) main.for
fl32 $(cflags) manq.for
fl32 $(cflags) mdr.for
fl32 $(cflags) mdr2.for
fl32 $(cflags) modif.for
fl32 $(cflags) mom.for
fl32 $(cflags) objct1.for
fl32 $(cflags) objct2.for
fl32 $(cflags) objpd1.for
fl32 $(cflags) objpd2.for
fl32 $(cflags) optis.for
fl32 $(cflags) paik.for
fl32 $(cflags) participation.for
fl32 $(cflags) pconti.for
fl32 $(cflags) pedge.for
fl32 $(cflags) pimpr.for
fl32 $(cflags) pinf1.for
fl32 $(cflags) pinf2.for
fl32 $(cflags) pinf3.for
fl32 $(cflags) pinteg.for
fl32 $(cflags) plaque.for
fl32 $(cflags) plimit.for
fl32 $(cflags) polrt.for
fl32 $(cflags) press.for
fl32 $(cflags) rang.for
fl32 $(cflags) rang2.for
fl32 $(cflags) recip.for
fl32 $(cflags) resolu.for
fl32 $(cflags) resul.for
fl32 $(cflags) resul2.for
fl32 $(cflags) save.for
fl32 $(cflags) sbega.for
fl32 $(cflags) sens.for
fl32 $(cflags) sensibcout.for
fl32 $(cflags) sensibcout2.for
fl32 $(cflags) sharedvar.for
fl32 $(cflags) sorti.for
fl32 $(cflags) stiff.for
fl32 $(cflags) system.for
fl32 $(cflags) ushull.for
fl32 $(cflags) vcos.for
vecto.for
vision.for
visionn.for
vsin.for

clean:

