subroutine deallocate_param_materiau()
use param_section

deallocate (e)
deallocate (eta)
deallocate (sigy)
deallocate (sigyadm)
deallocate (coefk)					
deallocate (spec)

deallocate (dref)	
deallocate (drefx) 
deallocate (drefy) 
deallocate (dref_b)
deallocate (dref_c)
deallocate (dref_l)
deallocate (c1)	
deallocate (c2)	
deallocate (c3)
deallocate (cout)
deallocate (c_pb)	
deallocate (c_tc)  
deallocate (c_tl)  
deallocate (dc1)	
deallocate (dw2)	
deallocate (dw3)	
deallocate (dw_b)	
deallocate (dw_c)  
deallocate (dw_l)  
deallocate (labour_cost)
deallocate (p10)   
deallocate (dp10)  
deallocate (p4)    
deallocate (dp4)   
deallocate (p5)    
deallocate (dp5)   
deallocate (p9x)   
deallocate (p9y)   
deallocate (dp9x)  
deallocate (dp9y)  
deallocate (ber)   
deallocate (bet)   
deallocate (p6)    
deallocate (p7)    
deallocate (c8)    
deallocate (dc8)
deallocate (ialr) 
deallocate (ialt)

return
end
