      SUBROUTINE SHEARYIELD(NEL,NETO,NVAR,NXIT,TAU,dTAU,SF,NTOT,
     *					  TAUA,dTAUA)


      IMPLICIT REAL*8 (A-H,O-Z)

	DIMENSION NVAR(NETO),NXIT(9,NETO)

	DIMENSION dTAUA(NTOT)
	
	DIMENSION TAU(NETO,3),dTAU(NETO,3,NETO)	

c	*****************************************************************************************************

	CALL ANNULD(dTAUA,NTOT)
	
	COEF=1.
	TAUMAX=MAX(DABS(TAU(NEL,1)),DABS(TAU(NEL,2)),DABS(TAU(NEL,3)))
	IF(DABS(TAU(NEL,1)).EQ.TAUMAX) THEN
	  TAUA=DABS(SF*TAU(NEL,1))
	  IF(TAUA.NE.(SF*TAU(NEL,1))) COEF=-1.
	  L1=0
	  DO IPAN=1,NETO
	    NBRXI=NVAR(IPAN)
		DO L=1,NBRXI
	      LL=NXIT(L,IPAN)
		  IF(LL.EQ.1) THEN
		    dTAUA(L1+L)=COEF*SF*dTAU(NEL,1,IPAN)
			GOTO 1
	      ENDIF
		ENDDO
    1	    L1=L1+NBRXI
	  ENDDO
	ELSEIF(DABS(TAU(NEL,2)).EQ.TAUMAX) THEN
	  TAUA=DABS(SF*TAU(NEL,2))
	  IF(TAUA.NE.(SF*TAU(NEL,2))) COEF=-1.
	  L1=0
	  DO IPAN=1,NETO
	    NBRXI=NVAR(IPAN)
		DO L=1,NBRXI
	      LL=NXIT(L,IPAN)
		  IF(LL.EQ.1) THEN
		    dTAUA(L1+L)=COEF*SF*dTAU(NEL,2,IPAN)
			GOTO 2
	      ENDIF
		ENDDO
    2	    L1=L1+NBRXI
	  ENDDO
	ELSEIF(DABS(TAU(NEL,3)).EQ.TAUMAX) THEN
	  TAUA=DABS(SF*TAU(NEL,3))
	  IF(TAUA.NE.(SF*TAU(NEL,3))) COEF=-1.
	  L1=0
	  DO IPAN=1,NETO
	    NBRXI=NVAR(IPAN)
		DO L=1,NBRXI
	      LL=NXIT(L,IPAN)
		  IF(LL.EQ.1) THEN
		    dTAUA(L1+L)=COEF*SF*dTAU(NEL,3,IPAN)
			GOTO 3
	      ENDIF
		ENDDO
    3	    L1=L1+NBRXI
	  ENDDO
	ENDIF	  

      RETURN
      END
